### PR TITLE
UTSW BioHPC private registry

### PR DESCRIPTION
**Pull request by dtrudg**
Remove dead randomroad registry - update to real BioHPC private registry I look after.

### CODE REVIEW

**Comment by dtrudg** [comment]
I'm confused about the CircleCI failure here. My `bundle exec jekyll s` works as expected locally.

image

**Comment by vsoch** [comment]
Me as well - circle appears to be looking for the old file (and it's not found) so it might be caching. I'll try rebuilding without cache, and then take a look locally.

**Comment by vsoch** [comment]
Just found the bug :)

**Comment by vsoch** [comment]
I was finding changed files from the commits, and as a result this included deleted too. So the bug was that it was attempting to read in the old (deleted) file when it should have checked that it existed first, and then just moved on.

**Comment by vsoch** [comment]
ok, I think the bug will be fixed with subsequent builds! I just viewed and tested locally and it looks great!! Woohoo!

**Pull request merged**
