### PR TITLE
(fix) remove container table

### LINKED ISSUE #13: Remove listing of containers
It's not reasonable to have a listing of containers, given CORS. We should just remove the table.

### PR DESCRIPTION
**Pull request by vladdoster**
- Removes CSS, JS, and HTML related to a registries container table

Closes #13

### CODE REVIEW

**Comment by vladdoster** [comment]
Whoops, need to update templates.

**Comment by vladdoster** [comment]
I can't tell if it is actually broken or maybe I'm doing something incorrectly.

When I browse the artifacts I get a 404 when browsing to a specific organization's registry. I assume this should not be the case?

How do you go about accessing the preview?

**Comment by vsoch** [comment]
Hmm it looks like too much was removed? https://50-101526766-gh.circle-artifacts.com/0/containers/registry/hms-rc_registry/index.html I haven't looked at the code in a while, but I'll take a look now and see if I can generate what we need.

**Comment by vsoch** [comment]
>  When I browse the artifacts I get a 404 when browsing to a specific organization's registry. I assume this should not be the case? How do you go about accessing the preview?

Very good question! So on an actual web server, a file in a folder like `containers/index.html` would render via the url `/containers/`. But since CircleCI isn't a webserver, those index.html exist (but the links that don't include them do not). So what you always have to do is navigate to the url, see the 404, then just add an index.html to the end to view the file directly.

**Comment by vladdoster** [comment]
Found the bug I think. All the code is on the page but rendering gets messed up due to cruft script tag.

image

**Comment by vsoch** [comment]
Ok I have a simple fix! Will open PR shortly.

**Comment by vsoch** [comment]
You actually don't need to do that much work - it's fixed just by renaming the private registry template to be the default. I'll open a PR now.

**Comment by vladdoster** [comment]
image

**Comment by vsoch** [comment]
I just wanted to say that I really appreciate you jumping on these - even if we didn't ultimately merge your efforts are really appreciated! I'm having fun working with you, even if just on these little things :)

**Comment by vladdoster** [comment]
I find the process very valuable. This case, in particular, exposed me to the idea that deleting code isn't always the most optimal way to remove something.

I would have said one could just go back through the commit history to get the code if it was needed again, but that would be more work later. Overall, your solution makes more sense long term.

**Pull request closed without merging**
